"""add s3 image keys

Revision ID: 1a6fd55298cf
Revises: a4badaa6937e
Create Date: 2026-09-24 12:10:24.135483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6fd55298cf'
down_revision: Union[str, Sequence[str], None] = 'a4badaa6937e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_authors', sa.Column('profile_image_key', sa.String(length=500), nullable=True))
    op.add_column('blogs', sa.Column('cover_image_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'cover_image_key')
    op.drop_column('blog_authors', 'profile_image_key')
    # ### end Alembic commands ###
