"""make course category optional

Revision ID: 803069f1a8bf
Revises: 95823889c322
Create Date: 2026-09-29 15:37:01.008172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803069f1a8bf'
down_revision: Union[str, Sequence[str], None] = '95823889c322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('courses', 'subcategory_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'subcategory_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('courses', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
